### PR TITLE
[fix] My pulls were no longer on top

### LINKED ISSUE #312: My Pulls should be at the top
We have some sorting to determine the order of PRs:
https://github.com/iFixit/pulldasher/blob/f9ac1c3d34f9cdd12afb5ede155d11f04407e01f/frontend/src/pulldasher/sort.ts#L4-L13

That's not working for me:
image

I don't have any filters on.

cc @danielbeardsley

### PR DESCRIPTION
**Pull request by danielbeardsley**
Fix unsorted columns, see commits for more info

Bug was introduced when I added `allOpenPulls` and returned the array without sorting
https://github.com/iFixit/pulldasher/pull/300/files#diff-4894e3876cc8c65384780c691d91fbbed9c96f3e8251e48fbf96429e24f173d5R51

Thanks @mlahargou for finding this!

Closes #312

### CODE REVIEW

**Comment by danielbeardsley** [comment]
QA: Sorting should now use this on all non-QA columns:
https://github.com/iFixit/pulldasher/blob/master/frontend/src/pulldasher/sort.ts#L4-L13

**Review by masonmcelvain — APPROVED** [review]
CR ✌🏻

**Comment by jordycosta** [comment]
CR 🌊 _TEST_

**Comment by jordycosta** [comment]
QA 🟢 

The sorting specifications shown [here](https://github.com/iFixit/pulldasher/blob/master/frontend/src/pulldasher/sort.ts#L4-L13) are now active ✔️ 

---

### Testing Procedure:
1. Checkout | merge with [`my-pulls-on-top-bug`](https://github.com/iFixit/pulldasher/tree/my-pulls-on-top-bug)
2. Launch **Pulldasher-dev** _([learn more](https://overlord.ifixit.com/Guide/How+to+test+Pulldasher+with+Puldasher-dev/1124#s5875))_
3. Test out each sorting case

> Your pull requests at the top
> Pull's you CR'd or QA'd on the bottom

---

### Screen Captures:

cr_

**Comment by batbattur** [comment]
CR 👍

**Pull request merged**
