### PR TITLE
Updates less to ^3.8.1 to pull in npm audit fixes

### PR DESCRIPTION
**Pull request by copperwall**
These changes were primarily done by `npm audit fix`.

### CODE REVIEW

**Comment by BaseInfinity** [comment]
CR 👙

**Comment by danielbeardsley** [comment]
CR 👍

**Comment by danielbeardsley** [comment]
Thanks @copperwall !!!

**Comment by addison-grant** [comment]
QA :sunny:

Checked out this branch and ran pulldasher with our data and did some visual inspections. :+1:

**Pull request merged**
