### PR TITLE
Pulldasher: Clarify webhook `secret` param

### PR DESCRIPTION
**Pull request by andyg0808**
The docs on this weren't clear on all the requirements to get the webhook working.

### CODE REVIEW

**Comment by zdmitchell** [comment]
CR :guitar:

**Comment by djmetzle** [comment]
CR :arrow_right_hook:

**Comment by danielbeardsley** [comment]
Thakns!

Soonish we should just use Github's method of validating the request is coming from them:
https://developer.github.com/webhooks/securing/#validating-payloads-from-github

Same idea (a pre-shared secret) but it uses hmac on the message body instead of comparing the value directly.

**Comment by batbattur** [comment]
QA 👍

**Pull request merged**
