### PR TITLE
navbar: show total pulls as well

### LINKED ISSUE #270: Nav bar pull count: show total and filtered count
Have the nav bar show both total and filtered counts: `56 open, 34 shown` or something similar.

### PR DESCRIPTION
**Pull request by danielbeardsley**
Now we show both total pulls *and* the numbered of pulls shown after the
filters.

Closes #270

### CODE REVIEW

**Review by andyg0808 — APPROVED** [review]

**Comment by andyg0808** [comment]
CR :goat: through b70eded

**Comment by deltuh-vee** [comment]
dev_block ✊ 
Could you make it more explicit as to what the numbers mean? It's a little vague to have a number followed by another number enclosed in parentheses.
CleanShot 2022-04-10 at 14 06 48

**Comment by danielbeardsley** [comment]
> Could you make it more explicit as to what the numbers mean? It's a little vague to have a number followed by another number enclosed in parentheses.

Heh, I went back and forth with the design a bunch, but didn't like the look of any of them.

* `open: 76 total: 86`
  * Implies that the gap is "closed" pulls
  * Takes up a lot of horizontal space
  
Oh! I have an idea... implementing.

**Comment by danielbeardsley** [comment]
Hows that? Moved it into a tooltip.

**Comment by danielbeardsley** [comment]
un_dev_block :+1:

**Review by andyg0808 — APPROVED** [review]

**Comment by andyg0808** [comment]
CR :goat: through c73e3be

**Comment by cdcline** [comment]
CR 👍

**Comment by deltuh-vee** [comment]
QA 🎬 
The number of Shown pulls is listed, along with the list of open pulls(hidden under a tooltip).

**Pull request merged**
