### PR TITLE
Notifications: detect missing feature

### PR DESCRIPTION
**Pull request by danielbeardsley**
If the feature isn't available, don't try to use it.

Noticing "undefined variable 'Notification'" errors on iPhones.

### CODE REVIEW

**Comment by jordycosta** [comment]
dev_block 🟥 

chrome_HWC2hJIGJ6

Still seeing this error 😕

**Comment by danielbeardsley** [comment]
un_dev_block :+1: 

Thanks for testing!

**Review by jarstelfox — APPROVED** [review]
CR 🌵

**Comment by jordycosta** [comment]
error

I'm surprised that I didn't catch this compile error sooner

https://github.com/iFixit/pulldasher/blob/6c543b5ad3286bb07ab7efcd64e824c3ca695e75/frontend/src/navbar.tsx#L66

---

It looks like https://github.com/iFixit/pulldasher/commit/b04fe8652bfd5d22b7b309426e29b768da5fbf2c introduced this

After removing line 66 (and the import on line 17) I was able to view **Pulldasher** on iOS

**Comment by danielbeardsley** [comment]
un_dev_block :+1:

**Comment by jarstelfox** [comment]
CR 🌵

**Review by jarstelfox — APPROVED** [review]
CR 🌵

**Comment by k0rvusk0r4x** [comment]
The errors noted above are no longer present.

QA 😺

**Pull request merged**
