### PR TITLE
Dates: deal with null values

### LINKED ISSUE #47: dates: allow nulls
[`dates--allow-nulls`](https://github.com/iFixit/pulldasher/compare/dates--allow-nulls)

### PR DESCRIPTION
**Pull request by danielbeardsley**
Previously every missing or null date field (from the github api)
would end up as 0 in the database instead of NULL because
we were always doing `new Date(thing.date)`.

I've extracted the most likely behavior into a utils function
and used it wherever it made sense. This was nearly everyplace besides
the client and places where we were explicitly comparing Date objects.

Closes #47

### CODE REVIEW

**Comment by BaseInfinity** [comment]
CR 🚲

**Comment by solflare** [comment]
CR :moon:

**Comment by davidrans** [comment]
CR ☕

**Comment by davidrans** [comment]
CR ☕

**Comment by danielbeardsley** [comment]
Derp. Forgot the Migration. Mind taking one more look? Thanks @davidrans !

**Comment by solflare** [comment]
CR :moon:

**Comment by danielbeardsley** [comment]
I ran the migration on cominor and it was fine. QA 👍

**Pull request merged**
