### PR TITLE
Package-lock.json: Run `npm update`

### PR DESCRIPTION
**Pull request by danielbeardsley**
And `npm audit fix`

Might as well keep it up to date.

### CODE REVIEW

**Comment by jarstelfox** [comment]
CR :cactus: but deploy_block :cactus: I’d like to make sure that none of the updates are breaking / could cause issues

**Comment by danielbeardsley** [comment]
QA 👍 

un_deploy_block 👍 

I merged this and the other pull together and ran the app. It served the main page will all the data just fine. I redelivered some webhooks and it did the right thing (and refreshed some pulls).

**Comment by sctice** [comment]
CR 🎏

**Comment by danielbeardsley** [comment]
dev_block 👍 

I noticed a bug and started tracing it down last night. The little pop-up that shows above the CR signatures was blank. This is how it usually looks:

image
 
But afterward (this pull) it pops up blank. We're still giving the html to the tooltip object, but it's popping up blank. I'm betting it's a css styling issue or something. All other usages of the tooltip seem to be working fine. Perhaps those are all using text and this one is using html?

**Comment by danielbeardsley** [comment]
Closing in favor of #161

**Pull request closed without merging**
