### PR TITLE
Make it Easier to Start Developing Pulldasher

### PR DESCRIPTION
**Pull request by alexottoboni**
Vagrant setups a VM with Docker and MySQL with the schema precreated to save
new developers time setting up a development environment.

You still have to create a Github Application though.

### CODE REVIEW

**Comment by kimarre** [comment]
A wild @alexottoboni appears!

**Comment by MooreGuy** [comment]
It might be nice to have the start and stop commands be using docker compose. I'm not sure if there was some reason that you avoided putting mysql into a container?

**Comment by MooreGuy** [comment]
I think docker-compose makes this setup pretty easy, but I have seen many people have problems with getting pulldasher running on their machines with docker. In the case that this provides an alternative for someone that can't get pulldasher running in docker, I'm all for it.

**Comment by MooreGuy** [comment]
CR :+1:

**Comment by copperwall** [comment]
Looks good to me :star:

**Comment by sterlinghirsh** [comment]
CR :zap:

**Comment by mlahargou** [comment]
Could I get some QA tips please?  Thanks! 😄

**Comment by alexottoboni** [comment]
Docker on Sierra (Mac) has a bug where the MySQL data volume can't be created in a container that I've run into a couple times setting up some other projects. Encapsulating it in a Ubuntu VM fixes it. Also having MySQL on the host VM is a little easier to setup than container to container networking. 

@mlahargou 
I tested it by running `vagrant up`, waiting it for finish successfully. `vagrant ssh` then editing the config to use the secrets I have for a repo with some dummy pull requests.** If you point your web browser to 192.168.33.10:8080 you should see pulldasher.

**I'm assuming you can just use the existing secrets iFixit uses on their running instance of pulldasher.

**Comment by evannoronha** [comment]
Silly question, is there a way to check out this branch if I have ifixit/pulldasher on my local machine?

**Comment by evannoronha** [comment]
Okay, I did the following on my local machine:
- Manually copied `Vagrantfile` in my pulldasher root directory
- copied our cominor pulldasher config into my pulldasher dir
- ran
   - `vagrant up`
   - `vagrant ssh`
   - `docker build /vagrant -t pulldasher:dev`
   - `./start-pulldasher`
- Navigated to http://192.168.33.10:8080/ on my browser and got:
   image

**Comment by alexottoboni** [comment]
Ah I forgot about this. I can take a look what the issue is this week.

**Comment by alexottoboni** [comment]
When you run `./start-pulldasher` what prints to the console?

**Comment by alexottoboni** [comment]
I'm closing this pullrequest for now. Merging to latest and running docker build gives me webpack errors.

**Pull request closed without merging**
