### PR TITLE
Ready Column: exclude pulls with no CI

### LINKED ISSUE #272: New frontend: Pulls with no CI are not deploy blocked
In the Old UI, a pull with no CI checks would end up in the deploy block column with a notice to deploy carefully. The new UI puts these pulls in the ready column.

### PR DESCRIPTION
**Pull request by danielbeardsley**
If a pull has no CI statuses and no required statuses, then it should be
in the deploy block column because likely it'll need some manual
intervention for deployment.

Closes #272

### CODE REVIEW

**Comment by jarstelfox** [comment]
CR 🌵 but I did notice there is no badge or anything indicating these pulls, not sure if you want one

**Comment by davidrans** [comment]
CR :coffee:

**Comment by deltuh-vee** [comment]
dev_block ✊ 
I think we should still have a badge to differentiate the pulls that have no CI between the ones that have been manually deploy blocked.

**Comment by danielbeardsley** [comment]
I refactored the logic a little bit, added some test data and added a flag.

**Comment by danielbeardsley** [comment]
image

**Comment by davidrans** [comment]
un_dev_block :+1:

**Review by davidrans — APPROVED** [review]
CR :coffee:

**Review by jarstelfox — APPROVED** [review]
CR 🌵

**Comment by deltuh-vee** [comment]
QA 🎬 
Badges now differentiate between manually deploy blocked pulls and pulls with no CI.

**Pull request merged**
