### PR TITLE
QA leader list: remove it

### LINKED ISSUE #276: Get rid of QA Leaders section
We agreed in retro to get rid of the QA Leaders section, since it's not really useful as a measure of QA output.
cc: @k0rvusk0r4x

### PR DESCRIPTION
**Pull request by danielbeardsley**
The QA team doesn't feel this is useful, so let's drop it and make the CR list longer.

image

Closes #276

### CODE REVIEW

**Review by ardelato — APPROVED** [review]
CR 👍

**Comment by Michelle5102** [comment]
I think it's worth revisiting [the discussion](https://ifixit.slack.com/archives/C90126AN4/p1649194632050299) from a few days ago about removing the CR leaders section. Expanding the list seems to go the opposite direction of some suggested changes in the thread, since it would effectively show how much each dev has CR'd. Maybe we could have a discussion about what to do with the CR leaders section at the dev meeting on Monday?

**Comment by danielbeardsley** [comment]
I vote for keeping it, it helps me scale my CRing and let's me know when I've not been helping out enough. I can imagine lots of improvements though:

* Show more personalized stats like
   * Number of my up-to-date CRs, out of date CRs
   * Number of CRs int he last 24 hours (as opposed to CRs on just pulls that are open)
   * Number of total pulls I've interacted with in the last 24 horus (made comments on or have a CR or block on)
* Have counts be based on time (last 24 hours) instead of just count them on the open pulls

**Comment by andyg0808** [comment]
To repeat my comments from the thread @Michelle5102 linked:
For CR, I find it helpful because I'm trying to balance the amount of CR I do with the amount of other coding. If I'm at the top of the leaderboard, I know that I'm doing my share. I also have used it a fair amount in the past to thank teammates for their contributions to the CR load.

If we wanted to redesign it so it was more like a nudge (only show green/yellow/red for the current user, so you know if you're doing your share), I could get behind that. That would eliminate the "how much did so-and-so do" bit.

For this PR, I'd suggest **limiting the number of folks shown to the top 5 or so,** just to focus on the positive "these folks have been doing a ton of the work."

**Review by andyg0808 — APPROVED** [review]

**Comment by andyg0808** [comment]
CR :goat: through fba3e6f

**Comment by erinemay** [comment]
@danielbeardsley I think more personalized stats, or different views of the metric would be more helpful. 

What's the actual current metric displayed here? Is it CR's per day? Per week? Active CR's currently on the board? 

It sounds like everyone wants a metric to quickly tell them where they stand relative to others in the dev-team CR ranking. I just want to make sure that the metric is actually providing that.

**Comment by danielbeardsley** [comment]
> Active CR's currently on the board?

Close. Total Active CRs. I admit, it's not that useful, they go out of date, pulls get merged, ...

> It sounds like everyone wants a metric to quickly tell them where they stand relative to others in the dev-team CR ranking. I just want to make sure that the metric is actually providing that.

I agree and if we can come up with a spec, we can totally implement it.

Maybe:
* Count of unique pulls you've made a signature on in the last 24 hours (be that dev block, CR, QA)
* Count of signatures you've made in in the last 24 hours (be that dev block, CR, QA)
* Count of just CRs in the last 24 hours (be that dev block, CR, QA)

**Comment by deltuh-vee** [comment]
dev_block ✊ 
I got this error when trying to deploy to pulldasher-dev.
CleanShot 2022-04-10 at 13 22 52

**Comment by davidrans** [comment]
I think Total Active CRs is a useless metric. What I want is:
 - How many CRs have I done in the last two weeks
 - What is the median amount of CR each team member has done in the last two weeks

For CR, what I would like to be shooting for is everybody doing roughly the same amount of CR. I don't want to be on bottom or on top of the leaderboard necessarily. 

I find this dashboard useful, currently, for figuring out whether I'm pulling my weight: https://dashboards.ifixit.com/d/ib-nEXlWz/github-metrics?orgId=1&fullscreen&panelId=12

I never look at the current leaderboard cause I don't think CRs on pulls that haven't been merged is useful.

**Comment by danielbeardsley** [comment]
> I think Total Active CRs is a useless metric. What I want is:

Sounds great! I'm game for a more useful leaderboard. Feel free to make an issue.

**Comment by danielbeardsley** [comment]
un_dev_block :+1: 

Not 100% sure why you got those (seemingly valid) errors and the CI build did not. But I fixed them.

**Review by andyg0808 — APPROVED** [review]

**Comment by andyg0808** [comment]
CR :goat: through d84265d

**Comment by jordycosta** [comment]
QA 🟢 

The QA leader list is now removed ✔️ 

---

### Testing Procedure:
1. Checkout | merge with [`qa-leader-list--remove-it`](https://github.com/iFixit/pulldasher/tree/qa-leader-list--remove-it)
2. Run the following script:
> `/home/ifixit/ifixit_scripts/update-pulldasher-dev --run . `
3. View the changes on https://pulldasher-dev.cominor.com/

---

### Screenshots:

QA_leaderboard_removal

**Comment by danielbeardsley** [comment]
Merging. It's gotten enough CR / QA. Further advancement of this feature should happen in a new issue.

**Pull request merged**
