### PR TITLE
Update pulldasher schema for `reviews.body`

### PR DESCRIPTION
**Pull request by addison-grant**
This is a follow-up to https://github.com/iFixit/ifixit/pull/38592
to keep the pulldasher repo up-to-date

qa_req 0 ~ this will be exercised in testing https://github.com/iFixit/ifixit/pull/38592

Connects #222

### CODE REVIEW

**Comment by ardelato** [comment]
@addison-grant any suggestions on how to QA this?

**Comment by addison-grant** [comment]
Let's mark it qa_req 0? I think this will be tested by testing https://github.com/iFixit/ifixit/pull/38592.

**Comment by addison-grant** [comment]
But deploy_block :sunny: on https://github.com/iFixit/ifixit/pull/38592 going out

**Comment by ardelato** [comment]
@addison-grant I down to mark it `qa_req_0`

**Comment by cdcline** [comment]
CR 👍

**Comment by hackalot805** [comment]
LGTM CR 💀

**Comment by k0rvusk0r4x** [comment]
https://github.com/iFixit/ifixit/pull/38592 has gone out. Does this need to be blocked on anything else?

**Comment by addison-grant** [comment]
> [iFixit/ifixit#38592](https://github.com/iFixit/ifixit/pull/38592) has gone out. Does this need to be blocked on anything else?

No, I think this should be good to merge!

**Pull request merged**
