### PR TITLE
Avatars: link to user profile pages on GH

### LINKED ISSUE #299: PR: Show author's avatar
* Show the user's avatar right before the `repo#number` in the top left of the pull card
* Have the existing *my-pull* star replace the avatar for your own pulls
* On hover, show the users username
* On click go to the user's profile page on github

CC @danielbeardsley @sterlinghirsh

### PR DESCRIPTION
**Pull request by danielbeardsley**
Have avatars in the leader list *and* the pull cards both link to the profile pages.

Closes #299

### CODE REVIEW

**Comment by jordycosta** [comment]
dev_block 🟥 

link2profile

Avatars in the leader list and pull cards aren't directing to the user's GitHub profile

```
export 'userProfileUrl' (imported as 'userProfileUrl') was not found in './utils' (possible exports: actionMessage, toDateString)
TS2305: Module '"./utils"' has no exported member 'userProfileUrl'.
```

**Comment by danielbeardsley** [comment]
Aack!  Thank you @jordycosta ! I forgot to commit some bits. It was running fine locally cause I had uncommitted stuff.

FYI, for QAing front-end-only changes, you can run just the frontend of pulldasher on you local computer:
https://github.com/iFixit/pulldasher#developing-pulldasher

un_dev_block :+1:

**Review by bhuminson — APPROVED** [review]
CR :dagger:

**Review by andyg0808 — APPROVED** [review]

**Comment by andyg0808** [comment]
CR :goat: through 13bf5bf

**Comment by jordycosta** [comment]
QA 🟢 

Avatars in the CR leader board and pull cards direct to the respective user's GitHub profile ✔️ 
> Note: It's not clear that the avatar on the pull card will direct to the profile
i.e. the hyperlink shown on hover is for the pull request itself; however, it still will direct to the GitHub profile

screencap

---

### Testing Procedure:
1. Checkout | merge with [`avatar--link-to-profile`](https://github.com/iFixit/pulldasher/tree/avatar--link-to-profile)
2. Navigate to https://pulldasher-dev.cominor.com _(use [this guide](https://overlord.ifixit.com/Guide/How+to+test+Pulldasher+with+Puldasher-dev/1124#s5875) if needed)_
3. Ensure that clicking on an avatar in the CR leader board or a pull card will direct to the user's GitHub profile

---

### Screen Capture:

capture (2)

**Pull request merged**
