### PR TITLE
jshint: Fix things jshint complained about

### LINKED ISSUE #49: jshint: fix all the things
[`jshint--fix-all-the-things`](https://github.com/iFixit/pulldasher/compare/jshint--fix-all-the-things)

### PR DESCRIPTION
**Pull request by danielbeardsley**
Mostly coding style, but there was one bug regarding using a variable
that wasn't defined!

Closes #49

### CODE REVIEW

**Comment by kwiens** [comment]
Should `jshint` be in a commit hook?

**Comment by danielbeardsley** [comment]
Done, see pull #50 --- hmm Maybe I should have added that to this pull.

**Comment by danielbeardsley** [comment]
Done. I will close that other pull.

**Comment by danielbeardsley** [comment]
Bam. Passes now!

**Comment by davidrans** [comment]
CR ☕

**Comment by copperwall** [comment]
CR :neato:

**Pull request merged**
