### PR TITLE
Drop repo name and owner

### PR DESCRIPTION
**Pull request by MooreGuy**
Now that repo is the new column that is being used in all of the tables, the old repo_name and repo_owner columns can be dropped for good.

QA: Run the migrations, then test all the normal features of pulldasher, signing off and having it update, moving pulls between columns, and test all the links to pulls and their build statuses

### CODE REVIEW

**Comment by danielj41** [comment]
CR 👍

**Comment by MooreGuy** [comment]
It is really ironic every time I make a pull that really confuses pulldasher. dev_block :+1: on tests

**Comment by MooreGuy** [comment]
un_dev_block :+1:

**Comment by danielj41** [comment]
CR 👍

**Comment by copperwall** [comment]
CR :fire:

**Comment by mlahargou** [comment]
Are you still planning on QAing this?

**Comment by MooreGuy** [comment]
Oh, yeah, I get distracted pretty easily though...

**Comment by MooreGuy** [comment]
I'm going to finish QAing it tonight, but live.

**Comment by MooreGuy** [comment]
QA :+1: Ran the migration, checked that it worked. Also pulls with a different head repo than the base work correctly!

**Comment by MooreGuy** [comment]
huh, refresh?

**Comment by MooreGuy** [comment]
CR :+1:

**Pull request merged**
