### PR TITLE
Commit Checks: Use new api location

### PR DESCRIPTION
**Pull request by danielbeardsley**
The old checks endpoint isn't supported by github's new Fine Grained
Personal Access Tokens; but this equivalent endpoint is.

### CODE REVIEW

**Comment by danielbeardsley** [comment]
QA :+1: 

Doesn't crash anymore when using a FAT!

**Comment by danielbeardsley** [comment]
dev_block :+1: 

No longer crashes, the but API results are a different shape and it seems to be considering them all "not started". Pause.

**Comment by danielbeardsley** [comment]
un_dev_block :+1: 

Had to combine two apis... resulting in six API requests where there used to be just one.

**Comment by danielbeardsley** [comment]
QA :+1: 

It's running and refreshing pulls correctly.

**Review by andyg0808 — APPROVED** [review]
CR :+1: 
Looks reasonable to me.

**Pull request merged**
