### PR TITLE
Add Personal View

### LINKED ISSUE #383: Create Personal View
To more easily focus on pulls you are involved in, have a button that toggles a filter which only shows pulls you've CRed, blocked,  QAed, or Authored.

Either add a new toolbar button or nest a few of the existing ones under a hamburger menu.

### PR DESCRIPTION
**Pull request by jordycosta**
### Overview:

https://github.com/iFixit/pulldasher/assets/95656772/00812794-b03f-4f95-9a6b-2be23c513277

This adds a button that will allow for filtering pulls that you have authored, wrote a signature on, or deploy/dev blocked

> Additional functionality can easily be added with this 

---

**QA**: [Testing Documentation](https://overlord.ifixit.com/Guide/How+to+test+Pulldasher+with+Pulldasher-dev/1124)

---
Closes #383

### CODE REVIEW

**Comment by jordycosta** [comment]
dev_block 🟨

**Review by aburke07 — APPROVED** [review]
CR :alien:

**Comment by jordycosta** [comment]
@aburke07 Sorry about that, I dropped the unused import in https://github.com/iFixit/pulldasher/pull/391/commits/2c8f4fea64cfeda71e1c2a5339e6bec0d22aac16 since I replaced that usage with a **Box** and **Text**

**Review by aburke07 — APPROVED** [review]
CR :alien:

**Comment by kthaler** [comment]
- Selecting the "Show Personal View" and pulldasher showed everything I have authored, wrote a signature on, or deploy/dev blocked.
- All the components work with the the Personal View option selected and unselected.
- "Show Personal View" also filters the "Recently Closed Pulls"
- Pulldasher continues to update in real time

QA 🦕  - This works great! Opens up the opportunity for so much new functionality.

**Comment by danielbeardsley** [comment]
Fantastic @jordycosta !!!

**Pull request merged**
