### PR TITLE
Parse associated Issue in Pull and update from the Issue

### PR DESCRIPTION
**Pull request by andyg0808**
Use the "Closes" and "Connects" keywords to figure out what Issue we should use. Does not write to GitHub, simply updates the Pull object for now.

### CODE REVIEW

**Comment by andyg0808** [comment]
deploy_block :+1: on #11

**Comment by andyg0808** [comment]
Connects #7

**Comment by danielbeardsley** [comment]
Rebased it on pull 11 after fixing that one up / merging master in.

**Comment by copperwall** [comment]
CR :fire:

**Comment by danielbeardsley** [comment]
Rebased the pull (no conflicts) to update the list of commits / diff.

**Pull request merged**
