### PR TITLE
chore: Add fixes from npm audit to package-lock.json

### PR DESCRIPTION
**Pull request by copperwall**
webpack-cli, css-loader, and lint-staged needed to be updated to patch some
vulnerable dependencies.

qa_req 0

### CODE REVIEW

**Comment by sctice** [comment]
🎉 👋

**Comment by sterlinghirsh** [comment]
CR :zap:

**Comment by BaseInfinity** [comment]
CR 👙

**Comment by copperwall** [comment]
Wow that was fast :)

**Comment by jacksonmcdaniel** [comment]
qa_req_0 ?

**Comment by mlahargou** [comment]
I think so.  deploy_block 📱 on making sure 👍

**Comment by kwiens** [comment]
un_deploy_block 👍 Just merge it and test it live!

**Comment by addison-grant** [comment]
deploy_block :sunny:

Running this in dev for a day to test

**Comment by addison-grant** [comment]
No one has reported any problems. Going to merge. un_deploy_block :sunny:

**Pull request merged**
